### ISSUE TITLE
New deployment strategy

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1060]
To cut down on the number of builds we're doing, we should stop building every site on every push. The only way to do this in Vercel is to use the ["ignored build step" option](https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel). I think we can detect the branch of every build and use that to determine when we should build member sites. Here's what I think should be the structure:

1. We continue to do all development work on feature branches. **On pushes to branches, we only build Oaklyn**.
2. We continue to merge all feature branches into `main`. **This builds Oaklyn in production and member sites in preview**.
3. We create a new branch, `stable`, that is the production branch for all member sites. When we're ready for a release of new features (weekly? biweekly?), we merge `main` into `stable`. **Member sites are built for production, Oaklyn is ignored**.

We'll need a good strategy to handle hotfixes that need to get merged into `stable` without a full feature release. Can't say I have a ton of experience with that, so I'm open to suggestions, and I'll do research.

**Comment by jacqui** [comment]
This all sounds good to me. For hotfixes, there are many philosophies, of course, but I think our strategy should be:

* make a hotfix branch off of `stable`
* debug, fix code, test in hotfix branch
* merge hotfix branch into `stable` _and_ `main`
* deploy stable

This is how I've most commonly worked in the past and I think it supports flexibility well while maintaining low risk deployment & development. 

We can still have non-production-ready features in feature branches, then tested + reviewed + accepted features in `main`, a `stable` branch that's always safe to deploy, and the ability to fix live production issues. These fixes make it back into any open feature branches when these are merged into `main`, or of course could be merged intentionally into a specific feature branch before it merges with `main`, I guess.
