### ISSUE TITLE
Need to register domains for Tiny Cloud for TinyMCE

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1063]

**Comment by jacqui** [comment]
This is done [in the Tiny Dashboard for TinyMCE](https://www.tiny.cloud/my-account/domains/). I added the following domains:

* angdiaryo.org
* austinvida.com
* blackbygod.org
* fivewardsmedia.com
* harveyworld.org
* spotlightschools.com
