### ISSUE TITLE
Don't replicate so much code in the homepage layout components

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#108]
Since we're [not going to have customizable streams anymore](https://github.com/news-catalyst/tinynews-tinycms/issues/36), the only piece of the homepage that needs to change based on the layout is the featured block. So the nav, stream, footer, etc. can all be handled in the page file, instead of duplicating them in the two separate components for the layout.

**Comment by jacqui** [comment]
Makes sense, on it.
