### ISSUE TITLE
Update organizations model to include domain

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#1098]
Part of #1085 

Similar to how the Vercel Platforms example has [a Site model with subdomain and domain info](https://github.com/vercel/platforms/blob/main/prisma/schema.prisma#L89) which its middleware uses to direct requests to the right `pages/_sites/[site]` folder, we will have to update our Organization model to include `subdomain` and `customDomain` fields.

I think this is also how we could scope (authenticate) requests to hasura through the webhook? (Determine that)

**Comment by TylerFisher** [comment]
Quick note here: I think we want both `subdomain` and `customDomain`. I've found that members like to build and test their site on a tinynewsco.org domain and then migrate to the custom when they're finished. Especially if they already have something existing at their own domain.

**Comment by jacqui** [comment]
> Quick note here: I think we want both `subdomain` and `customDomain`. I've found that members like to build and test their site on a tinynewsco.org domain and then migrate to the custom when they're finished. Especially if they already have something existing at their own domain.

Thanks - I updated the description based on this.
