### ISSUE TITLE
Vercel Platforms: Article stream still getting wrong category headers

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1128]
<img width="863" alt="Screen Shot 2022-03-08 at 11 09 11 AM" src="https://user-images.githubusercontent.com/1077075/157277619-24be881f-0084-4395-a4be-27dd1f2888fb.png">

**Comment by jacqui** [comment]
<img width="863" alt="Screen Shot 2022-03-21 at 11 07 20 am" src="https://user-images.githubusercontent.com/3397/159191864-a9cb2deb-3f8b-4aa7-b0fb-60ab578372ef.png">

looks like this is fixed already!
