### ISSUE TITLE
Document good slug practice

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1140]
I've noticed members writing custom slugs sometimes. We should be clearer that:

1. We will create slugs automatically based on the headline if left blank, no need to do this if you don't want to
2. If you do want to create slugs, you should follow good slug hygiene. Slugs should be all lowercase, with words hyphenated: `this-is-a-slug`. Slugs should not contain non-alphanumeric characters beyond hyphens.

**Comment by pdeharo333** [comment]
Complete
