### ISSUE TITLE
Rethink regeneration strategy to account for on-demand regeneration

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1141]
Instead of revalidating all of our pages so frequently, we should use on-demand static regeneration, just launched in next.js 12.1, to rebuild pages when we know they've changed. See docs [here](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta).

This will require a new API endpoint that allows us to regenerate pages. We should regenerate on the following events:

1. Publish events from Google Docs: we should regenerate the article page, the homepage, category page, author pages, and tag pages associated with the article.
2. Saves from TinyCMS homepage editor: regenerate the homepage
3. Saves from TinyCMS nav builder: regenerate every page
4. Saves from TinyCMS settings: two options:
    - Rebuild every page no matter what changed
    - Get fancy and regenerate based on what changed, e.g. only regenerate the donate page if payment options changed, but regenerate everything if the color scheme changed.

With this in place, we should up the revalidate times on every page to something much less aggressive, like 10 minutes or something.

My main question here is whether it's feasible to regenerate every page on a site manually.

**Comment by jacqui** [comment]
I've started working on this today. As a test I'm trying [the example revalidate api endpoint code](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta) with modifications for our purposes - using the api token found in the settings table, like all our other endpoints do, for a start.

I've run into an issue related to platforms/subdomain/"site" feature of our stack though:

```
[middleware] updated path: /_sites/localhost:3000/about
error - TypeError: Expected "3000" to be a string
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 149 ms (704 modules)
Error: Failed to revalidate /about?site=next-tinynewsdemo
    at unstable_revalidate (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/api-utils/node.js:228:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handler (webpack-internal:///(api)/./pages/api/revalidate.js:38:5)
    at async Object.apiResolver (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async DevServer.runApi (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/next-server.js:386:9)
    at async Object.fn (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/router.js:228:32)
    at async DevServer.run (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/base-server.js:600:29)
    at async DevServer.run (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/dev/next-dev-server.js:445:20)
    at async DevServer.handleRequest (/Users/jacqui/Projects/newscatalyst/frontend-site/node_modules/next/dist/server/base-server.js:307:20)
```

I need to figure out a way to pass the site into the revalidate call. So far query param and full URL do not work and/or error. Checking the `next.js` [source code for this unstable_revalidate](https://github.com/vercel/next.js/search?q=unstable_revalidate) function shows me it only accepts a url path, so hrm. I'm trying out workarounds in our middleware (pass a `site` query param for instance and use it in the revalidated url).

**Comment by jacqui** [comment]
Okay, I was able to get the revalidate endpoint working with the following code changes, which could work for us, I think. I want to review the approach again tomorrow with fresh eyes before I move forward though:

```
diff --git a/pages/_middleware.js b/pages/_middleware.js
index 10b9143..2e3ea2a 100644
--- a/pages/_middleware.js
+++ b/pages/_middleware.js
@@ -2,7 +2,7 @@ import { NextResponse } from 'next/server';
 
 export default function middleware(req) {
   const url = req.nextUrl.clone(); // clone the request url
-  const { pathname } = req.nextUrl; // get pathname of request (e.g. /blog-slug)
+  const { pathname, searchParams } = req.nextUrl; // get pathname of request (e.g. /blog-slug)
   const hostname = req.headers.get('host'); // get hostname of request (e.g. demo.vercel.pub)
 
   if (pathname.includes('/en-US')) {
@@ -10,7 +10,7 @@ export default function middleware(req) {
     return NextResponse.redirect(url);
   }
 
-  const currentHost = hostname
+  let currentHost = hostname
     .replace(`.localhost:3000`, '')
     .replace(`.tinynewsco.dev:3000`, '')
     .replace(`.tinynewsco.org:3000`, '')
@@ -19,6 +19,10 @@ export default function middleware(req) {
     .replace(`.vercel.app`, '')
     .replace(`.vercel.app:3000`, ''); // TBD if we need to change this
 
+  if (currentHost === 'localhost:3000' && searchParams) {
+    currentHost = searchParams.get('site');
+  }
+
   if (
     (!pathname.includes('.') || pathname.includes('.xml')) && // exclude all files in the public folder
     !pathname.startsWith('/api') // exclude all API routes
diff --git a/pages/api/revalidate.js b/pages/api/revalidate.js
index 123a8c9..a4471e6 100644
--- a/pages/api/revalidate.js
+++ b/pages/api/revalidate.js
@@ -30,8 +30,8 @@ export default async function handler(req, res) {
   }
 
   try {
-    // await res.unstable_revalidate(`${pathToRevalidate}?site=${site}`);
-    await res.unstable_revalidate(pathToRevalidate);
+    await res.unstable_revalidate(`${pathToRevalidate}?site=${site}`);
+    // await res.unstable_revalidate(pathToRevalidate);
     return res.json({ revalidated: true });
   } catch (err) {
     console.error(err);
```

Noting this here so I can pick it up first thing in the morning.

**Comment by jacqui** [comment]
Another update from me: I slept on it and the approach above, with some code cleanup/small mods, works well for our revalidate API endpoint.

Progress so far:

* wrote a `revalidate` function in `lib/utils.js` that takes a path, site, and api secret
* now using this function in the TinyCMS homepage editor to revalidate the homepage

Next up, revalidating pages associated with an article on `publish` which I think should happen directly in our sidebar document API endpoint for publish: the actual article page, the homepage, category page, author pages, and tag pages. To do this, I'll need to generate the paths for each of those pages, which shouldn't be too hard. 

After that, though, there's the issue of revalidating every single page on a site. That will take awhile :-/ In order to achieve that goal, though, we will need a way of generating all paths per site, so all articles, author/category/tag pages, and static pages.

**Comment by TylerFisher** [comment]
Yeah, I think the concern with just using a deploy hook is that eventually, we'd be rebuilding hundreds of sites unnecessarily. That will put an undue load on our Hasura and Vercel bandwidth. 

A Lambda seems like a reasonable way to handle this.

**Comment by jacqui** [comment]
We have a lambda: https://github.com/news-catalyst/revalidate-paths
