### ISSUE TITLE
Figure out fix for vercel preview urls

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#1149]
We got an ssl error trying to view preview urls in vercel using the site subdomains. Maybe this is due to some misconfig or bug in the middleware?

**Comment by jacqui** [comment]
Well, it's not even hitting our app so I don't think it's a problem with our middleware, unfortunately. I spent some time on this today and someone else has run into this exact issue: https://github.com/vercel/platforms/discussions/85

I upvoted the discussion. I'm not sure how to get around it outside of ... maybe adding support for a `?site=${site}` query param but that would entail a significant amount of code changes to make it work site-wide.

**Comment by TylerFisher** [comment]
I'd rather just have a second Vercel project that builds off of the staging database on "production"
