### ISSUE TITLE
Release: 0.2.0

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1187]
- [Next SEO migration](https://github.com/news-catalyst/next-tinynewsdemo/issues/1137)
- [Authorized email domains fix](https://github.com/news-catalyst/next-tinynewsdemo/issues/1154)
- ~[Release newsletter archives feature](https://github.com/news-catalyst/next-tinynewsdemo/issues/1186)~

**Comment by TylerFisher** [comment]
Moving newsletter archives to next release.

**Comment by jacqui** [comment]
Release is out and all sites look great. TinyCMS auth verified (by me) as working in production on all sites.
