### ISSUE TITLE
Homepage editor: Invariant failed: Unable to find drag handle

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#119]
Seems like some sort of race condition. When I load the homepage editor, the drag and drop doesn't load and this error is in the console

<img width="637" alt="Screen Shot 2020-09-10 at 4 39 55 PM" src="https://user-images.githubusercontent.com/1077075/92802180-46f64a00-f384-11ea-9fa6-385c5d7d1dff.png">

If I make a trivial change in the app to force a hot reload, the app works. I haven't dug deep enough into react-beautiful-dnd to figure out why this is happening yet.

**Comment by jacqui** [comment]
We're no longer using drag & drop, closing this issue 🎉
