### ISSUE TITLE
react-dates and react-twitter-embed imcompatible with react 17

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1191]
Next.js now requires react 17, but a couple of our React plugins don't support react 17. `react-twitter-embed` is a simple fix: https://github.com/capaj/react-tweet-embed is an easy replacement I've already implemented locally.

`react-dates` poses a harder problem, but I'm trying some alternatives.

**Comment by jacqui** [comment]
the two options (react-twitter-embed and react-datepicker) you found and implemented work great for me, I commented on the open PR for next-seo and in slack too 👍
