### ISSUE TITLE
Instagram reels only load as a preview

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1196]
Nancy try loading an Instagram reel, and only this preview loaded. That suggests to me something about when the Facebook SDK script loads, but I'm not sure.

<img width="788" alt="Screen Shot 2022-04-11 at 10 31 38 AM" src="https://user-images.githubusercontent.com/1077075/162783396-265e0897-3d11-4c24-a7b3-a124c77dadc3.png">

I was able to fix this for Nancy by using the post URL instead of the reel URL. That's the same URL except it's `instagram.com/p/...` instead of `instagram.com/reel/...`.

Maybe the easiest way to fix this is to just rewrite `/reel/` URLs to use `/p/` instead. They have the same ID string after no matter which you use.

**Comment by chelsea-tnc** [comment]
Covered during walkthrough with Tyler. See 1:05:21.

**Comment by chelsea-tnc** [comment]
Confirmed with @pilar333 that this issue was fixed. Example can be seen [here](https://www.austinvida.com/articles/cultura/selenabirthday2022). Thanks, Pilar!
