### ISSUE TITLE
PressPass login wall

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#120]

**Comment by jacqui** [comment]
Apologies if this is basic, but it's been a bit since I've worked with PressPass or thought about this integration!

What exactly needs to happen here? We want to use PressPass to handle access to the tinycms? One of the next things I want to do is handle protecting `/tinycms` on all the tnc deployed sites from the public internet & that involves figuring out how to manage access and authenticate, of course.

Is this along the lines of what you were thinking with this issue?

**Comment by TylerFisher** [comment]
@jacqui Yes, exactly.

We want to wall off anything in the TinyCMS with a PressPass login. When a user logs in with PressPass, we need to make sure they're a member of the PressPass organization that matches the Tiny News org they're trying to log into (this protects against any PressPass user logging into any TinyCMS). Once that check passes, we keep your login stored in a session so you can navigate around the TinyCMS.

For implementation, I see two routes:

1. We have a [passport strategy for PressPass](https://github.com/news-catalyst/passport-presspass). There's a [canonical next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-passport/pages/api) on how to use passport with next.js, though that doesn't show how to do things with OAuth. Still, that could get us most of the way there. But we'd have to write our own session storage to keep people logged in between pages and such.

2. The other option is [NextAuth.js](https://next-auth.js.org/), which more tightly integrates with Next. The session integration looks really nice and it handles determining sign-in state with a simple React hook. The downside here is we have to setup a [custom OAuth provider](https://next-auth.js.org/configuration/providers#using-a-custom-provider), but that looks pretty straightforward.

@jacqui Which do you think will be easier?

**Comment by TylerFisher** [comment]
I took a look through PressPass just to remind myself how we'll do things on that end. I think we should just develop against the deployed test PressPass at presspass.dev rather than try to make things work through local Docker containers.

Steps to get the test version of this all working:

0. Get @jacqui an admin-level account on presspass.dev
1. Setup an OAuth client for the TinyCMS. This will give us a client ID to use as part of the login process. This is done in the Django admin at server.presspass.dev/admin. We want the client type to be public, and the response type to be `code`. Over time, we will want to add every deployed TinyCMS's auth endpoints to Redirect URIs.
2. Create a TinyCMS entitlement in the Django admin (this ties the OAuth Client to PressPass plans).
3. Create a Tiny News Collective Plan in the Django admin. The plan should be free, for groups only, and give access to the TinyCMS entitlement created above.
4. Create an Oaklyn Observer organization and add Tyler and Jacqui's user accounts as admins in the Django admin.
5. Log into the PressPass frontend and subscribe the Oaklyn Observer to the Tiny News Collective plan. (This should be easier, but I don't think it's doable in the Django admin. Will investigate.)

I'll do all of the above tomorrow.
