### ISSUE TITLE
Why is `ScriptError: Exception: Attribute provided with no value: url` happening when publishing on Oaklyn?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#1230]

**Comment by TylerFisher** [comment]
Articles still publish, but this is what is returned. Seems like the add-on can't construct the published URL?

**Comment by jacqui** [comment]
I'm looking into this - first thing I noticed was that almost all of the config was blank for this organization (next-tinynewsdemo/oaklyn) in the admin tools sidebar, including the publish url. The only values present were for the document API. I've filled all of the values back in and will test out publishing.

**Comment by jacqui** [comment]
Yeah, that was it: the sidebar wasn't totally configured. I'm not sure how that happened, it's been a minute since I've had to change any of the settings in the Admin Tools. Anyway, that's what caused the script error, and it is fixed now for Oaklyn/next-tinynewsdemo.
