### ISSUE TITLE
Newsletter Archive page is publishing 'in review' newsletters 

### ISSUE THREAD

**Issue by pdeharo333** [news-catalyst/next-tinynewsdemo#1283]
Tested a couple scenarios in staging with Letterhead. When a newsletter is in 'review' and you schedule a time/day you'd like it published, it publishes it on the archive page after deployment. But, when it's in 'draft' status it doesn't publish. [This](https://github.com/news-catalyst/next-tinynewsdemo/blob/381161f282906fb6a67ca0b6442fe345d85db98e/script/build-newsletter-editions.js) is where I'm looking to see why its picking up the newsletters in review and not just published. 

Also to remove a newsletter from the archived page by deleting it in Hasura, you need to remove it in Letterhead first, otherwise it will not work.

**Comment by pdeharo333** [comment]
https://github.com/news-catalyst/next-tinynewsdemo/pull/1286

**Comment by pdeharo333** [comment]
Merged these changes into Main to test in staging site:
[PR 1
](https://github.com/news-catalyst/next-tinynewsdemo/commit/cdb0e6ccf721b8c656d7722b23573e75e6bb22eb
)[PR 2](https://github.com/news-catalyst/next-tinynewsdemo/commit/f71e88492de86fc33305c95cfa3b54d12825b17a)

To test: 
1. Go to Letterhead and create a published newsletter (when creating make sure to add the mailing block and unsubscribe link to be able to schedule and publish). You'll notice there is already newsletters for 'draft' 'review' and in 'schedule.'
2. Redeploy staging in Vercel so it updates the Archive Newsletter Page
3. You should notice that your newly published newsletter has been added to the archive page

While testing the welcome newsletter, I noticed it wasn't actually posting on folks archive page. In that previous example where we thought Nancy's welcome letter was posting it was actually a newsletter that she created as a welcome one. I also checked other orgs that have Welcome Letters  [BBG](https://app.tryletterhead.com/authoring/newsletters?event=1&type=welcome-letter&status=6), [Five Wards Media](https://app.tryletterhead.com/authoring/newsletters/2352) and confirmed this. So if you test and everything looks good this should be okay to push to Prod.

**Comment by chelsea-tnc** [comment]
Verified that welcome letters aren't being published. We reported an issue with the Letterhead API where sometimes welcome letters are included in the API response and sometimes they aren't. This is why we were seeing some welcome letters logged for some channels and not for others.
