### ISSUE TITLE
why is the homepage missing the featured article intermittently?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#142]
Not sure it's actually intermittent... but I loaded the homepage after successful deploy and saw this:

<img width="1388" alt="Screen Shot 2020-10-16 at 7 58 29 am" src="https://user-images.githubusercontent.com/3397/96185581-d72c3e00-0f85-11eb-8831-9508c250f3fa.png">

A few minutes later, the featured article was there, though.

**Comment by TylerFisher** [comment]
Still seeing this, kind of annoying for demo purposes but again, our homepage design is going to change enough that I'm not really concerned about fixing it. I'll leave it open, but it's not a high priority.
