### ISSUE TITLE
Coral instance doesn't work on production

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#165]
I think we just need to clear `next-tinynewsdemo.vercel.app` on that Heroku installation. I don't have access to it, could you add that @jacqui?

**Comment by jacqui** [comment]
Yep, exactly.

I added "The Oaklyn Observer" as a site under the "News Catalyst" organisation in Coral Talk (https://coral-talk-news-catalyst.herokuapp.com/admin/configure/organization/sites/bfa6ddfc-eb85-47bf-9215-df725daeb28f), specified `https://next-tinynewsdemo.vercel.app, http://next-tinynewsdemo.vercel.app` for the site URLs, reloaded the article page and voilà, the comment form appeared.

I feel like we went through this a couple months ago... but... the dashboard in Coral says you have access. I just made you an admin, though this also felt familiar. Let me know if you have any luck accessing it when/if you have a chance. In the meantime, you should be able to see Coral loading successfully on articles for the demo (https://next-tinynewsdemo.vercel.app/articles/politics/heres-how-philadelphia-public-schools-will-operate-this-fall for instance).

https://coral-talk-news-catalyst.herokuapp.com/admin/community

<img width="1055" alt="Screen Shot 2020-10-27 at 2 07 11 pm" src="https://user-images.githubusercontent.com/3397/97252346-e18be900-185d-11eb-890a-abd420689da5.png">
