### ISSUE TITLE
Configurable fonts and colors

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#172]
TBD

* choose from a set of typography options
* similarly choose from a set of colour combos 
* one or both of these should allow custom overrides

**Comment by TylerFisher** [comment]
This should go in the site metadata model, and based on the value, we should set a class at the outer level of the app that creates the style.

**Comment by TylerFisher** [comment]
Once #261 is merged, this can be started. There are three color classes: `colorone`, `colortwo`, `colorthree`; and four style classes: `styleone`, `styletwo`, `stylethree`, `stylefour`.

TBD how we'll do custom overrides, but we'll definitely want color overrides, and probably font overrides.
