### ISSUE TITLE
How should we localize hardcoded text?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#221]
Things like the word "By" in bylines, the format of dates, "The Latest", etc.

**Comment by jacqui** [comment]
Good question. I'm thinking we might want to use a plugin for handling hardcoded text & translations - I found one that looks very similar to how I've done that sort of thing in the past, even down to using the same `t()` function wherever the text is displayed:  https://github.com/vinissimus/next-translate

Not sure how it all fits together just yet, but I'll take that on (trying out the plugin, etc) as part of resolving this issue.
