### ISSUE TITLE
Reporter bio images?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#231]
<img width="377" alt="Screen Shot 2020-12-22 at 1 50 47 pm" src="https://user-images.githubusercontent.com/3397/102843200-cfdd5100-445c-11eb-876a-8d324d48aa03.png">

Are we going to need to support author bio photos? 

Since we're already asking for a twitter handle, should we aim to use the twitter profile photo?

And/or will we need to support image uploads for authors in the tinycms?

**Comment by TylerFisher** [comment]
Yeah, I think we want bio images. We have it modeled in Webiny, just never implemented uploading in the TinyCMS.

**Comment by jacqui** [comment]
After some discussion, I'm trying the following approach:

* a single assets bucket for TNC orgs
  * top-level namespace `assets.tinynews.org/oaklyn` for example
* no back-end service
* aws cognito + iam + s3
  * following this guide https://medium.com/@shresthshruti09/uploading-files-in-aws-s3-bucket-through-javascript-sdk-with-progress-bar-d2a4b3ee77b5
* and simple front-end file uploader
