### ISSUE TITLE
"Topics We Cover" vs top right nav

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#232]
<img width="460" alt="Screen Shot 2020-12-22 at 2 03 28 pm" src="https://user-images.githubusercontent.com/3397/102843975-8261e380-445e-11eb-9a54-e3543ac5d52f.png">

Should these be the same set of links in both spots?

**Comment by TylerFisher** [comment]
Yeah, good point. Not sure if we want or need this sidebar. Is there something else that would make sense here? I'm hesitant to put a list of tags because that could go on forever.

**Comment by jacqui** [comment]
Just getting back to this. 

I see that there's currently a slightly different set of links in the nav vs the sidebar (https://the-oaklyn-observer-7d8okxfjq.vercel.app/) which is making me feel a bit differently about how this looks. I agree on the tags list.

I think we should revisit this once real news orgs start joining up with us and we have better use cases for this design.
