### ISSUE TITLE
Preview is redirecting to the wrong article

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#254]
http://localhost:3000/api/preview?secret=DUNGEONSDRAGONS&slug=kensingtons-last-minute-gift-guide redirects to http://localhost:3000/preview/business/franny-lous-porch-starts-a-gofundme-to-buy-their-building

I also can't get any console logs to show up in the API route. No idea what's going on here.

**Comment by TylerFisher** [comment]
Looks like this issue is a little deeper in the stack, see https://github.com/news-catalyst/reproducible-tinynews-content-api/issues/65

**Comment by jacqui** [comment]
Wild. The query was working for me, but, pointing at the same API, the preview is still weirdly redirecting me.

I've just noticed the preview URL doesn't include the category here. Not sure why that would break it in this way, but maybe a clue. Still investigating.

**Comment by jacqui** [comment]
Aha it was missing the locale.
