### ISSUE TITLE
Protect against "fake" bylines like "Staff Reporter"

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#281]
In discussion about editorial policies, we think it's best to require "real" bylines as much as possible and protect against people putting controversial or political content behind anonymous "staff reporter" bylines. We could protect against this a bit by putting some custom form validation in the tinyCMS. 

This isn't pressing or immediate, just logging the discussion.

**Comment by jacqui** [comment]
We're talking about basic pattern matching in the CMS, not letting you save an author with a name like "staff reporter"? That's easy enough to do.

Can we put together a list of terms to validate against? The author name would be fully matched against these, not partial:

* staff reporter
* reporter
* editor
* staff writer

...

**Comment by TylerFisher** [comment]
Yeah, I think that's how we'd do it.
