### ISSUE TITLE
Articles that get unpublished still appear on homepage in featured blocks

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#336]
This results in a link that leads to an error because the article page can't be built.

Without doing some really expensive queries on publish, I'm not sure how to rectify this. Certainly, this is an edge case, but would lead to some pretty unexpected behavior.

**Comment by jacqui** [comment]
@TylerFisher what if we made it so you had to remove the article from a featured spot on the homepage before being able to un-publish it?

So then, in the sidebar in Google Docs, when retrieving an article, also check which articles are currently featured. If this document corresponds to a featured article:

* display a message like "Featured on homepage" in the sidebar
* hide the un-publish button
