### ISSUE TITLE
Support Google News Sitemaps

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#366]
So sitemaps, built in #365, are one thing. But Google News, of course, requires a [whole different sitemap](https://support.google.com/news/publisher-center/answer/9606710). As far as I can tell, `next-sitemap` can't handle the nested properties you need here. I've opened [an issue](https://github.com/iamvishnusankar/next-sitemap/issues/110) to see if there's any traction, but if not, it's something we'll have to do separately.

**Comment by jacqui** [comment]
Doesn't look like there's any movement on the next-sitemap issue. I +1'd it just now (kinda late but... maybe it'll help). Should we keep this on the backburner or try to generate the Google News sitemap ourselves?
