### ISSUE TITLE
Twitter embed is broken

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#382]

**Comment by jacqui** [comment]
Where is the broken embed? I just added a tweet to the article about the cellist and see it rendering okay:

[google doc](https://docs.google.com/document/d/1M1UZ1BKx1rDdzr7Pu4oH_AU2qS2GirToCQ5uqNBVjVM/edit)

[localhost article link](http://localhost:3000/articles/news/local-artist-daniel-de-jesus-releases-new-album-these-songs-represent-an-analysis-of-my-own-psyche)

<img width="737" alt="Screen Shot 2021-03-12 at 12 02 12 pm" src="https://user-images.githubusercontent.com/3397/110876012-c9a79400-832a-11eb-97d0-663c1db23403.png">

<img width="773" alt="Screen Shot 2021-03-12 at 12 02 30 pm" src="https://user-images.githubusercontent.com/3397/110876033-d62bec80-832a-11eb-8016-27538ddbcc18.png">

**Comment by TylerFisher** [comment]
Looks like this is a Firefox issue. I'll take a look into that.

**Comment by jacqui** [comment]
Yeah as we discussed on Slack this is due to strict protection in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1417921
