### ISSUE TITLE
Authors are required on stories even if custom byline is passed

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#384]
We should require one of author or custom byline, but not always author

**Comment by jacqui** [comment]
@TylerFisher  I just tried this and was able to:

* preview & publish with **authors** and without **a custom byline**
* preview & publish a second time without **authors** and with **a custom byline**
* preview & publish a third time with **authors** and without **a custom byline**

I believe you but am not sure how this happened... so I've added an extra console.log with hopefully helpful data that will be triggered when the "author or custom byline is required" message is displayed. This is version 69, code in master, and has been published for the add-on.

Can you tell me what document this happened on or anything else?

<img width="332" alt="Screen Shot 2021-03-12 at 1 40 18 pm" src="https://user-images.githubusercontent.com/3397/110884665-8e609180-8339-11eb-85c4-7dc470c8172f.png">

<img width="320" alt="Screen Shot 2021-03-12 at 1 48 10 pm" src="https://user-images.githubusercontent.com/3397/110884695-97516300-8339-11eb-9241-62ad5c8341d8.png">

**Comment by jacqui** [comment]
Oh! This is actually a problem on the front-end. I understood this issue originally to mean there was a problem with the validation on the sidebar.

Rendering a page with a custom byline and **no** authors results in an error: `TypeError: Cannot read property 'author' of undefined`
