### ISSUE TITLE
Republish site triggers?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#389]
Given the issues we're already aware of with changes to articles not being reflected on the homepage - unpublishing articles, changing or adding main images to articles - I think we should revisit the idea of republishing the site by posting to a vercel webhook.

The triggers that come to mind for me are:

* publish an article - currently the article page renders (due to fallback handling) but article doesn't show up on homepage stream, category, tag or author index pages
* unpublish an article - so the article is removed from all index pages including homepage
* change featured articles on homepage - this already happens, just thought I'd log it as a trigger
* change homepage layout - also already happens

**Comment by TylerFisher** [comment]
Yeah, I suppose it can't hurt to fire a republish. The article page would still get the benefits of the fallback handling even if we fire a republish. Let's do it.
