### ISSUE TITLE
Build tag pages

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#39]
Now that we have tags and are linking to them, let's build proper tag pages. Here's how:

1. In `lib/articles.js`, add tags to the `LIST_ARTICLES` query. Create a new function `listAllArticlesByTag` that takes a `tag` argument. Call the `LIST_ARTICLES` query, and filter the data you receive by the tag argument. Return your filtered data. This will be the most difficult part of this process.
2. Create a new file at `pages/tags/[title].js`. Define two functions: `getStaticProps` and `getStaticPaths`. 
3. In `getStaticProps`, call the `listAllArticlesByTag` function you just created and return a props object with the articles inside. Check out how this works in `pages/articles/[id].js` for an example.
4. In `getStaticPaths`, call `listAllTags` from `lib/articles.js`. Return an object with these tags inside. Look at `pages/articles/[id].js for an example.
5. Create your TagPage React component in the same file. Use the `<Layout>` component to wrap the page, and use the articles props to build a list of articles. Use the `articleLink` component you've already built.

This is very complicated! Take your time, and make use of the [next.js docs](https://nextjs.org/docs/basic-features/pages) when you get confused. Good luck!

If you get done, you can do the same thing with the new Category model. Categories work the same way as tags.

**Comment by TylerFisher** [comment]
We'll need to revise our model with some slugs to get this totally right. Leaving the PR open until we have the data model correct.

**Comment by jacqui** [comment]
I've added the `slug` text field to [the Tag content model in webiny](https://d1tj6tnba0qfzt.cloudfront.net/admin/cms/content-models/5f2a09fa84556900089a4222).

Is there a branch for this in-progress tag work so I can test what's already been done with this data model change?

**Comment by jacqui** [comment]
Pretty sure this is now wrapped up and the PR ready for review. Tag pages are linked under `/tag/{tag.slug}`
