### ISSUE TITLE
Analytics: newsletter stats

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#400]
Breaking this one out of issue #392 

**Newsletter subscription:**

* Views over past 30 days
* Subscriptions over past 30 days
* Conversion rate over past 30 days
* Most popular pages for newsletter subscriptions over past 30 days (i.e., what stories are converting?)
* Newsletter subscriptions by audience segment (i.e., what types of users are converting? Donors? Frequent readers?)

**To Do:**

- [x] get a mailchimp api key
- [x] views over past 30 days: **GA**  track event category "NTG newsletter" action "newsletter modal impression 1"
- [x] views over past 30 days could also be email opens: **Mailchimp** not sure which endpoint; it breaks up emails sent into campaigns, so get campaign (https://mailchimp.com/developer/marketing/api/campaigns/get-campaign-info/) might work with its `report_summary` data
- [x] subscribe form validated: **GA** track event category "NTG newsletter" action "newsletter signup"
- [x] subscriptions: **Mailchimp** I think this is the 'members' API endpoint https://mailchimp.com/developer/marketing/api/list-members/list-members-info/ using query `status=subscribed`
- [x] conversion rate: todo
- [x] most popular pages: todo, but this seems like a **GA** source
- [x] subs by audience segment: todo

**Comment by jacqui** [comment]
@TylerFisher how do we figure the conversion rate? Is that the (number of signups / emails sent) * 100 (I googled, I don't really know anything about this). Or is this something I need to dig into in GA, which has a "conversions" menu item...?

Also, what do you have in mind for the audience segments? Mailchimp lets you split mailing list recipients into segments, and this is then retrievable in the API (https://mailchimp.com/developer/marketing/api/list-segments/). GA also has audience demographics and other details, of course.

**Comment by TylerFisher** [comment]
I think by conversion rate I meant signups / impressions (or views of the modal)

**Comment by TylerFisher** [comment]
I'm not sure we'll do audience segmentation in Mailchimp too much. I think the only segments we're concerned about are those we're defining as custom dimensions in GA.

So subs by segment is purely a GA thing. How many people who read 2-3 posts subscribed? 4-6? etc.

Sidenote: I took the audience segments from Memberkit. Worth reading Brian's doc [here](https://docs.google.com/document/d/1U02dAFbOAxSMQeMBCHeJbWHaHI_W6daSRPE6WaR5hAI/edit#heading=h.gvufkidjh3n).
