### ISSUE TITLE
Analytics: reading depth data

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#405]
### Reading depth

- Overall reading depth averages (we have events firing for every quarter of a story page)
- Most-read stories (highest percentage of 100% depth events)

**Comment by jacqui** [comment]
@TylerFisher as a starting point, I have this data in the tinycms analytics now:

<img width="1306" alt="Screen Shot 2021-03-23 at 3 00 30 pm" src="https://user-images.githubusercontent.com/3397/112090960-939ac780-8be8-11eb-824d-c71a40c79eac.png">

For "overall reading depth averages" do we want to say something like, 90% of readers read 25% of articles, 31% read 100% of articles?

For most-read, am I simply tallying the % of all hits to each article that made it to 100% depth and ordering in reverse? So in the above screenshot (approximate math in my head) that would be: kensington gift guide & cooper river at the top, collingswood, homepage. Should homepage `/` be in this list?

**Comment by TylerFisher** [comment]
I think `/` should not be in this list.

Your sorting math makes sense -- % of all hits that made it to 100% depth and ordering in reverse.
