### ISSUE TITLE
Locale configuration is a little sloppy

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#412]

**Comment by TylerFisher** [comment]
This is because locales are defined in `next.config.js`, which needs to pull that from somewhere else instead of hardcoding.

**Comment by TylerFisher** [comment]
I tentatively fixed this in https://github.com/news-catalyst/next-tinynewsdemo/commit/fff24a6484f717e803d920c45c51bb6bfab361a5. That means we have both an env var and database records defining which locales a site publishes in. I don't love that, but I don't love doing a database query to configure our next.js config either. Open to other ideas if you have them, @jacqui.

**Comment by jacqui** [comment]
Argh this is a bit tricky. I forgot about the next config i18n section. I'm thinking this should be handled in the bootstrap-a-new-site process (which I think still needs finesse). I can work on this once analytics are sorted.

**Comment by TylerFisher** [comment]
Renamed this to be more representative of the issue now.
