### ISSUE TITLE
Deploy app to vercel and see how it goes

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#45]
https://vercel.com/

**Comment by jacqui** [comment]
<img width="1143" alt="Screen Shot 2020-07-30 at 4 14 26 pm" src="https://user-images.githubusercontent.com/3397/88887477-ce2da980-d27f-11ea-8766-03d3056880b0.png">

Got there eventually :)

**Comment by jacqui** [comment]
URL: https://next-tinynewsdemo.vercel.app/
