### ISSUE TITLE
How do we configure the homepage?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#46]
I don't know if this ends up being a Google Apps Script thing or a separate custom app that talks to Webiny, but I'm logging the issue here.

We need some way for users to feature a story on the homepage, or potentially determine the selection of stories on the entire homepage. Some of this will be dependent on whatever design we implement later, but we need a place for the data. In the future, we could support multiple homepage layouts/configurations.

**Comment by jacqui** [comment]
My idea for this is to create a simple homepage editor with two components:

1. A sidebar listing available articles (maybe most recently published, descending order) with a search form. This list of articles would be draggable.
2. A homepage with droppable spots for featuring articles.

I started a little nextjs app to do this with `react-beautiful-dnd` that borrows the basic graphql setup from this next-tinynewsdemo.

<img width="782" alt="Screen Shot 2020-07-31 at 1 46 47 pm" src="https://user-images.githubusercontent.com/3397/88998149-b95f1d80-d334-11ea-9cb7-95da7e4726e0.png">

You can't tell in the screenshot but the articles are draggable. I didn't finish this, but it wouldn't take too long to do. I figure we should chat first. The data could live in webiny, I think... that would be ideal at least.

Also, this kind of homepage editor could be part of the front-end app and live under `/admin` or whatever, with authentication for that route, if we wanted to keep it all together.

I think any implementation of this in Google Docs would be a pain for people to use, but maybe I'm not being imaginative enough? I could see each doc having a featured flag in the sidebar, but then how do you turn those off? You don't really want to click through each article...

I like the idea of combining search with drag & drop as it lets you filter the full articles list to find what you're looking for and visually confirms your choices. A wrinkle: the homepage "droppable" view should look like the homepage, so we'd have to be careful about reusing components and styles between the two.

What do you think @TylerFisher ? I can commit the code I started on today if you think this is a decent direction to go in.

**Comment by TylerFisher** [comment]
Closing in favor of the repo we have now
