### ISSUE TITLE
Analytics: urls with query strings

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#480]
<img width="925" alt="Screen Shot 2021-04-23 at 9 32 32 am" src="https://user-images.githubusercontent.com/3397/115797285-eb5e6580-a416-11eb-8752-3925605cee11.png">

<img width="944" alt="Screen Shot 2021-04-23 at 9 34 01 am" src="https://user-images.githubusercontent.com/3397/115797338-0b8e2480-a417-11eb-8942-71dc45be68dd.png">

The same article is showing up multiple times for page views, once without a query string, then again with query string values, multiple times. I'm not 100% clear on whether the page view counts should be combined - the first set with identical values is making me wonder.

**Comment by TylerFisher** [comment]
Good call, they should be combined. We can exclude query params we know about (like the Mailchimp ones) following the steps [here](https://www.searchdiscovery.com/blog/url-query-parameters-in-ga/).
