### ISSUE TITLE
Analytics: tracking localized urls vs urls for default locale 

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#481]
<img width="960" alt="Screen Shot 2021-04-23 at 9 35 56 am" src="https://user-images.githubusercontent.com/3397/115797626-b1da2a00-a417-11eb-8283-667027a68787.png">

<img width="916" alt="Screen Shot 2021-04-23 at 9 36 08 am" src="https://user-images.githubusercontent.com/3397/115797630-b43c8400-a417-11eb-8e83-f0471de72ac3.png">

I'm not sure we should track these separately.

**Comment by TylerFisher** [comment]
Yeah, hm. This one's tricky. I guess we could remove `/[default-locale]` if we see it when we send the pageview call?
