### ISSUE TITLE
Can't get all authors on about page

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#486]
I have no idea what is causing this issue, but whenever I try to call the Hasura API route for listing all authors on the about page, the promise doesn't resolve and I can't use the data. I add this to `getStaticProps`:

```
let authors = [];   
const { authorErrors, authorData } = await hasuraListAllAuthors(locale);
if (authorErrors) {
  console.error(authorErrors);
}
authors = authorData.authors;
```

Setting the authors variable errors because `authorData` is undefined. However, if I set a timeout in the `hasuraListAllAuthors` function console logging the result of the query, I get the resolved promise with the correct data.

**Comment by jacqui** [comment]
I updated the code in PR #488 to list all the site's defined authors on the about page. Instead of creating an additional request for this, though, I added the authors to the query for get page: it was already retrieving the site categories and metadata.
