### ISSUE TITLE
Static page `getStaticProps` results in recursion

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#487]
Not sure what's happening here, but I was trying to style the static page templates, and the published static page just recurses over and over again. It freezes up localhost to the point where I have to kill the process by the pid number. Seems to work on production though.

**Comment by jacqui** [comment]
I'm a little confused by this issue but I did at least find a problem with the static pages:

1. The static path generation for the pages under `/static` was wrong - it shouldn't have been adding `/static/` to the page slugs, my silly mistake
2. I didn't get this recursion/freezing error on these pages, using `yarn dev` or `yarn build` + `yarn start` so I'm hesitant to say that I've fixed the issue you ran into.

Hopefully this fixes it for you? I pushed my code to the branch in PR #488
