### ISSUE TITLE
TNC github repo setup?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#489]
Have we discussed how we should setup each TNC org in vercel as far as linking to a github repo?

Each org will have a vercel project with its own environment variables setup.

If we include a github repo, every push to that repo will result in a deployment. This is scoped to branch, so we could make it only on pushes to master, or some custom "emergency fixes only in production" type of branch (or scheduled maintenance, or both). 

If we don't include a github repo, how are we going to push out any necessary updates?

Wanted to jot this down now as it came up during my automation of vercel setup for each TNC in the bootstrap step.

**Comment by TylerFisher** [comment]
Can we assign each organization to this repo, like we have the three current test deployments? I don't foresee any need to customize code per organization.

**Comment by jacqui** [comment]
Okay that's what I've coded the bootstrap command to do with vercel.
