### ISSUE TITLE
New org setup: press pass configuration steps needed?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#509]
I need to confirm what has to happen in PressPass in order to setup a new Tiny News Org. The instructions that I wrote have me totally confused - they start with:

```
1. Create an oauth client in PressPass - note the assigned slug, it’s important for the next steps
```

I assume I meant add a client here: https://server.presspass.dev/admin/oidc_provider/client/add/

The current list of clients does not include our test orgs, though, so if this is required step one, how are those working? I'm wondering if I wrote this incorrectly and really meant `Create an organization in Presspass` instead.

**Comment by TylerFisher** [comment]
Ah, yeah, it's not oauth client, it's organization.
