### ISSUE TITLE
Vercel project creation via API sometimes fails

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#512]
Not sure why but I don't believe this error message:

```
[invalid_project_name] Unable to create Vercel project 'Monthly Popcorn' because: The name of a Project can only contain up to 100 alphanumeric lowercase characters and hyphens.
```

**Comment by TylerFisher** [comment]
This also happened to me today.

**Comment by TylerFisher** [comment]
Oh, ha, the error message is actually accurate. 100 alphanumeric **lowercase** characters. We should use the slug, not the name, for Vercel projects.
