### ISSUE TITLE
Does our caching strategy actually work on production?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#607]
In our vercel builds, this error occurs over and over again, suggesting that we can't actually read from the filesystem like we think we can, so we're hitting the letterhead API over and over. This probably isn't a huge deal right now, but once a site has hundreds and hundreds of pages to build, could become problematic.

<img width="893" alt="Screen Shot 2021-05-25 at 1 59 55 PM" src="https://user-images.githubusercontent.com/1077075/119546178-a1dc9f80-bd61-11eb-8bf1-aff75c02253d.png">

**Comment by jacqui** [comment]
Hey @TylerFisher I haven't been able to find this happening in any of the vercel builds. Where did you see it? So far it looks like the builds are working okay. I went back 20 days in the build logs, checking both preview and production builds. 

I would like to see the output from `node script/populate.js` earlier in a build that has this error - maybe it wasn't writing the file correctly?
