### ISSUE TITLE
Where did image nodes go?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#61]
For some reason, with [this article](http://localhost:3000/articles/us/heres-how-philadelphia-public-schools-will-operate-this-fall), images aren't showing up for me despite image nodes being available in the CMS API.

From the API playground, I see the image as the first node in the body:

<img width="794" alt="Screen Shot 2020-08-03 at 3 12 53 PM" src="https://user-images.githubusercontent.com/1077075/89218357-e4977600-d59b-11ea-941a-c896cb733f2e.png">

But when I log the response to the console from `lib/articles.js`, I don't see that node anymore.

<img width="551" alt="Screen Shot 2020-08-03 at 3 13 55 PM" src="https://user-images.githubusercontent.com/1077075/89218410-f7aa4600-d59b-11ea-98a9-34b1bb39cf4f.png">

**Comment by TylerFisher** [comment]
Okay, broke this down a little more. When I _list_ articles from the API, I get the images. When I get the article specifically, the images are gone weird!

<img width="1654" alt="Screen Shot 2020-08-03 at 3 17 54 PM" src="https://user-images.githubusercontent.com/1077075/89218721-89b24e80-d59c-11ea-91e0-c0dabcf874ae.png">

**Comment by TylerFisher** [comment]
Even weirder... this doesn't happen with our article, which has images.

**Comment by TylerFisher** [comment]
The only thing I can guess here is it has something to do with Webiny's "rich text" field... maybe we should use a "long text" field so it doesn't completely break?

**Comment by jacqui** [comment]
Argh that sounds about right that it's because of the rich text. Maybe changing to a long text will result in the webiny admin being usable too (could be useful in a pinch). I wish they offered a `data` type.
