### ISSUE TITLE
Clean up vercel deployments

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#613]
I think we only need three deployments on Vercel right now:

- `next-tinynewsdemo`: the main testing environment
- `tiny-news-curriculum`: the curriculum site
- `tinynewscollective`: the marketing site, which is built off a whole separate repo, but exists in our Vercel account.

Are we using `bello` for anything? Mariko had plans for `returning-home-to-nakano` as an example site, but I don't think that's happening anymore.

**Comment by jacqui** [comment]
* definitely not using bello, I forgot that was still up on vercel; I deleted it
* I asked Mariko about the nakano site to confirm it's cool for me to delete it

**Comment by jacqui** [comment]
Mariko confirmed it was fine to delete Nakano. Vercel deployments are now cleaned up!
