### ISSUE TITLE
Is it possible to turn off preview deployments for some vercel environments?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#626]
I worry that if we always have preview deployments on for every publication, we're going to get really clogged up in deploys.

**Comment by jacqui** [comment]
I haven't found a way to turn off preview deployments. It seems to be the default, and it definitely seems like a feature of the platform.

I agree with you though, we don't want to be deploying to all the orgs on every push to any branch.

After doing some digging, I think we could do something like this on the TNC org vercel projects:

https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel#with-a-script

I'll try it now.
