### ISSUE TITLE
Per-org setup needed for wherebyus api?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#632]
I was testing out the preview deployment script on a test org ("bello") when I noticed this error:

```
FetchError: invalid json response body at https://api.whereby.us/catalyst-test/api/v1/channels/catalyst-test/ads reason: Unexpected token W in JSON at position 0
```

I created this org using an `.env.local` slightly modified from my oaklyn settings; maybe I need a different url for the wherebyus/letterhead API?

**Comment by TylerFisher** [comment]
The URL to the API changed: https://api.tryletterhead.com/catalyst-test/api/v1/channels/catalyst-test/ads
