### ISSUE TITLE
Is there a lighter way to pull out main image for homepage and streams?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#682]
Currently, we're loading the entire contents of every article into our homepage and stream pages (categories, tags, etc.) in order to pull out the main image to display. Is there an lighter way of doing this? I see two ways:

1. Can you query the JSON via graphQL, and just get the image directly?
2. Add a `mainImage` field to article translations, and when we parse in the Google Doc, put it there instead of as a node in `content`.

**Comment by jacqui** [comment]
I think you figured this much out earlier, but I had a look [at Hasura's graphql support of JSONB fields](https://hasura.io/blog/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/), and it is indeed limited.

I think the best way to accomplish this is to add a mainImage field to the article translations table and store the data at publish time. I'll get started on this now.
