### ISSUE TITLE
Coral embed does not load in Firefox

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#709]
I'm guessing Firefox blocks the script loading process

**Comment by jacqui** [comment]
Huh, strange: it loads fine for me on `main` branch localhost, but on https://next-tinynewsdemo.vercel.app/ I'm seeing it try to load off of the old herokuapp url. Investigating...

**Comment by jacqui** [comment]
Aha I figured it out - Vercel was setup to deploy to production from the `master` branch which is now named `main`. Changed it! Trying to deploy now.

**Comment by jacqui** [comment]
<img width="1149" alt="Screen Shot 2021-07-28 at 7 40 10 am" src="https://user-images.githubusercontent.com/3397/127231789-d667f98d-6152-47cd-904e-8bf9a4d12e79.png">

Coral embed rendering in FF on localhost.

**Comment by jacqui** [comment]
Production site on Vercel is now up-to-date, but the coral embed script needs to be loaded behind https, so I'm on it now.

**Comment by jacqui** [comment]
Tyler is going to set up coral.tinynewsco.org subdomain with an ssl cert tomorrow. The subdomain should be a CNAME for [the load balancer](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#LoadBalancers:sort=loadBalancerName) currently running on coral-talk-lb-1654697893.us-east-1.elb.amazonaws.com.

Once that's done, I can [add an HTTPS listener in the AWS console](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#ELBListeners:type=app;loadBalancerName=coral-talk-lb;loadBalancerId=11f572f69ad896b0;accountId=049206021755)

**Comment by jacqui** [comment]
New issue: I have to figure out how to configure the ELB so [the embed is allowed](https://support.mozilla.org/en-US/kb/xframe-neterror-page).

<img width="1084" alt="Screen Shot 2021-07-29 at 7 45 40 am" src="https://user-images.githubusercontent.com/3397/127400374-a7c0071f-cd1b-45d4-8859-3f76e28f9fb9.png">

**Comment by jacqui** [comment]
Got it! 

<img width="1098" alt="Screen Shot 2021-07-29 at 9 04 48 am" src="https://user-images.githubusercontent.com/3397/127407346-c8d05db9-be9c-4367-86d8-50992181d8fd.png">
