### ISSUE TITLE
Rethink category page path

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#722]
The naked `/[slug]` path + incremental static generation means any spammed path would force Vercel to try to build the page, even if it's gibberish like `/apwiehgwapiohe`. That could cause some issue with the bandwidth limits we have on our account. Would it be better to protect from this by mounting category pages at `/categories/[slug]`? Or `/articles/[slug]`?

**Comment by TylerFisher** [comment]
Let's do `/categories/[slug]`

**Comment by jacqui** [comment]
I agree that `/categories/[slug]` makes the most sense 👍
