### ISSUE TITLE
Archive page

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#723]
Right now, the homepage shows the ten latest articles plus any featured articles. Other than category/author/tag pages, there's no way to get to older stories. We should have an archive features that lets people see older articles. The easiest version of this is to just dump all stories onto a page and live with the size of it. We could also implement a paginated query and display 20 articles per page or something.

**Comment by jacqui** [comment]
@TylerFisher Good point, I hadn't thought of the older stories... of course we need to provide a way to get there, doh. I think we should paginate from the start. My question is "previous"/"next" links or infinite scroll ("load more")?

**Comment by TylerFisher** [comment]
I think prev/next, I wouldn't want to have to hit the Hasura API live to populate the infinite scroll.
