### ISSUE TITLE
Bootstrap env issues

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#766]
I tested bootstrapping a new org and saw a few small problems with the env that is generated:

1. the google private key doesn't come through. It's a multiline var in my environment, and I only get the first one: `GOOGLE_CREDENTIALS_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----`
2. `AUTHORIZED_EMAIL_DOMAINS` should include the domain passed to the script
3. Should we be making a whole new AWS bucket for assets? Will that still get passed to our Cloudfront distro? I get `TNC_AWS_BUCKET_NAME` as `tnc-uploads-${slug}`
4. `LOCALES` did not match what I passed. I passed just `en-US` and get `en-US,es`. This causes build errors as it doesn't match the bootstrapped metadata.
5. `GA_TRACKING_ID` does not match what I see in the analytics dashboard.
6. `NEXT_PUBLIC_SITE_URL` is `localhost:3000`, not the URL I passed

**Comment by jacqui** [comment]
Updates:

* **email:** the authorized email domain is now taken from the URL by parsing the URL for its hostname, checking if it starts with "www." and removing it; so `https://www.test1.org` becomes `test1.org`
* **locales:** the script was trying to concat the given locale option with the previously set one; not sure why I was doing that, but I fixed it so only command line option values will be used: `-l en-US,en-GB,en-AU` creates 3 locales, `-l en-US` creates 1.
* **bucket name:** thanks for catching the s3 bucket issue - it should only be the top level directory that changes, the bucket name should remain the same.
* **site url:** another thing I missed! I'm now setting this to the given URL
* **GA Tracking ID:** this was happening towards the end, asynchronously, so I changed it to be the first thing that runs, waits, and then returns the new tracking ID, which is then used while generating the new environment.

I'll work on the credentials issue next.
