### ISSUE TITLE
On sites with two locales, add "Read in [other language]" link

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#776]
Because users may not have the proper locale set up (for Ang Diaryo's Tagalog readers, this is almost a guarantee), we want to provide handy links on every page to get to the Tagalog version (or vice versa). This link would open the current page in the new language.

**Comment by jacqui** [comment]
Where else do we want this link to appear? Do we want a special or more prominent version on the homepage?

And I suppose we'll want the link on the following hard-coded static pages:

* [ ] About page
* [ ] Donate page
* [ ] Thank You page
