### ISSUE TITLE
yarn vs npm

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#794]
The test build on [the latest PR](https://github.com/news-catalyst/next-tinynewsdemo/pull/793) fails because package-lock.json doesn't match package.json. I used yarn to add stuff recently, so yarn.lock was what got updated. Seems we should default to always using npm from now on so tests run. Any reason this is a bad idea?

**Comment by jacqui** [comment]
I don't know anything about it being a bad idea... I've been a little confused about which to use actually. Picking one seems like the right move - I'll use npm instead of yarn as well.

**Comment by jacqui** [comment]
I've updated vercel to use `npm run build` instead of `yarn build` fyi.
