### ISSUE TITLE
rich text editor for tinycms

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#796]
right now the landing dek is using markdown, but we should support something easier to work with.

**Comment by jacqui** [comment]
_RE: rich text, there was a JS lib that looked like a rich text editor but was actually markdown in the background, makes everything easy_

**Comment by TylerFisher** [comment]
We would want this for anything we call a description (newsletter cards, membership cards, etc.) in settings, the landing page dek, and author bios.
