### ISSUE TITLE
Take a stab at Pico

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#85]
I couldn't get it fully working, but I may have the configuration set up wrong. My [Pico take two branch](https://github.com/news-catalyst/next-tinynewsdemo/pull/68) has it loading on the page but nothing happens.

**Comment by jacqui** [comment]
Okay I'll see if I have any luck.

**Comment by TylerFisher** [comment]
Thanks for taking a look.

For what it's worth, I had a full demo of [MonkeyPod](https://monkeypod.io/) today, which has a fundraising system built in. It's not quite as integrated as something like Pico, but it's pretty good, and might do the trick for us. (It also does a whole suite of backroom accounting that we are really interested in from a finance perspective, and having it all integrated would be nice for bookkeeping reasons.)

**Comment by jacqui** [comment]
Cool. I'd feel better about putting all these tiny news co's on a platform that seemed more stable than Pico does, at least at this point. Looking forward to checking out MonkeyPod.
