### ISSUE TITLE
The API crashes... all the time?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#89]
I've started regularly having the issue when I'm trying to work on something and end up refreshing a lot that the API starts returning 502 errors and I have to wait a few minutes for everything to cool down. Maybe there's some resource we have to up in Webiny?

**Comment by jacqui** [comment]
Argh really? I've seen it 502 occasionally. Hrm. I'm looking into the configuration and at any docs Webiny provides on best practices for reliable API deployment... the docs I'm finding so far are very minimal. I'll check the webiny slack as well.

**Comment by jacqui** [comment]
Actually, @TylerFisher I'm not sure that I'm looking at the right AWS account here for the currently deployed content delivery API :-/. I might have created my own newscatalyst AWS account back when I was trialing CMS options including webiny... the API GW & CloudFront setups I can see were launched back in April.

Can you help me figure out how to login to the right management console tomorrow so I can try to find what the problem is with the crashing API? In the meantime <checks issues on a couple repos> I have plenty to do 🤭

**Comment by jacqui** [comment]
<img width="851" alt="Screen Shot 2020-08-24 at 9 12 40 am" src="https://user-images.githubusercontent.com/3397/90991098-f93ebb00-e5e9-11ea-868e-7757d15632ba.png">

Hah, I find that search result (webiny slack) surprising...

**Comment by TylerFisher** [comment]
Ah, yeah, it's on my AWS account. I'll give you a login on Slack later today. I took a look at the lambda functions and API gateways. There's a lot going on, so it's hard to figure out exactly where to look, but there's a few errors on the `cmsContent` lambda function.

<img width="1570" alt="Screen Shot 2020-08-24 at 4 31 04 PM" src="https://user-images.githubusercontent.com/1077075/91093323-468d4d80-e627-11ea-906a-02a1ed00cd44.png">

**Comment by TylerFisher** [comment]
Not sure how there's 1,040 invocations of the function at one point in time...
<img width="493" alt="Screen Shot 2020-08-24 at 4 32 35 PM" src="https://user-images.githubusercontent.com/1077075/91093463-78061900-e627-11ea-88b9-4b68cc7cdd5c.png">

**Comment by jacqui** [comment]
1,040 invocations seems very high. 

Well, I have access to AWS now - thanks. I enabled more detailed metrics in CW and will be looking for issues today. So far I haven't found much. I found the errors reported in that dashboard (around 01:05UTC on 2020-08-24 for example) but the CW logs were... extremely minimal. 

I see that webiny is setup with "debug" turned on for the api (https://github.com/news-catalyst/tinynews-contentapi/blob/master/api/resources.js#L6). Hrm...

**Comment by TylerFisher** [comment]
FWIW, I've been working with stuff all week and haven't seen this once.

**Comment by TylerFisher** [comment]
Via the webiny slack and an unrelated issue, I now know why this is happening:

<img width="944" alt="Screen Shot 2020-09-11 at 12 57 17 PM" src="https://user-images.githubusercontent.com/1077075/92952680-65188480-f42e-11ea-99bb-14c0db0b877a.png">

I had multiple of those tabs open while this was happening. Gonna close this now.
