### ISSUE TITLE
Better handling of ads in specially formatted text?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#929]
<img width="775" alt="Screen Shot 2021-11-01 at 9 34 34 am" src="https://user-images.githubusercontent.com/3397/139603410-48619e40-2470-4bc7-ade8-2487e2c395cd.png">

Should we avoid inserting ads in this kind of text?

**Comment by TylerFisher** [comment]
Yeah, I think so.
