### ISSUE TITLE
limit analytics page views table rows?

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#953]
Now that there's real data pouring into GA it's easier to spot areas of the tinycms analytics dashboard that should be improved... though I'm not the analytics expert for sure!

I think this table should be limited as a start:

<img width="1027" alt="Screen Shot 2021-11-09 at 11 25 23 am" src="https://user-images.githubusercontent.com/3397/140839373-417c6ef1-d8bc-4540-a358-68a4127fa2cb.png">

I had to zoom _way_ out to fit it into a screenshot.

armchair expert idea: I think it could be interesting to see the most viewed **articles** separate from the most viewed author pages, category pages, etc., while also including a top 10 or so most viewed pages across all types. What do you think @TylerFisher ?

**Comment by TylerFisher** [comment]
I love that idea. Ship it.
